### ISSUE TITLE
Add Affinity support

### ISSUE THREAD

**Issue by jbrz0** [webkul/coolhue#2]
I ported colours to .afpalette file for Affinity Designer/ Affinity Photo gradients file. If you want to add it to your README with the Photoshop/sketch gradients [https://github.com/brz0/cool-hue-affinity](https://github.com/brz0/cool-hue-affinity)

**Comment by webkul-nitish** [comment]
coolHue is still in beta and more gradients are one the way. Still we'll be looking into this.
Thanks for your effort!

**Comment by jbrz0** [comment]
Cool, good to know. Feel free to use that file if you need it
